#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   download and prepare utorrent for snap
#
# Date: Feb 14 2018
#

dlut () {
    wget --accept "*.exe" --content-disposition --trust-server-names http://download-hr.utorrent.com/track/stable/endpoint/utorrent/os/windows &> /dev/null
}

mkut () {
    mkdir ./{wine-platform,bin} && mkdir -p usr/share/{pixmaps,applications}
    7z x uTorrent.exe Carrier.exe -o"usr/share/utorrent"
    mv usr/share/utorrent/Carrier.exe usr/share/utorrent/utorrent.exe
    find "usr" -type d -execdir chmod 755 {} +
    wrestool -x -t3 -n62 -R usr/share/utorrent/utorrent.exe > usr/share/pixmaps/utorrent.png
}

mkdsk () {
cat > utorrent.desktop <<'EOF1'
[Desktop Entry]
Name=µTorrent
GenericName=BitTorrent Client
Comment=The world's most popular BitTorrent client
Encoding=UTF-8
Version=3.5.4.44846
Type=Application
Terminal=false
Icon=${SNAP}/usr/share/pixmaps/utorrent.png
Exec=utorrent %U
StartupWMClass=utorrent.exe
Categories=Network;FileTransfer;P2P;
MimeType=application/x-bittorrent;x-scheme-handler/magnet;
EOF1
}

dlut
mkut
mkdsk
mv utorrent bin && mv utorrent.desktop usr/share/applications && cp -R -p {bin,usr,wine-platform} $SNAPCRAFT_PART_INSTALL