#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   download and prepare utorrent for snap
#
# Date: Feb 14 2018
#

dlut () {
    wget --accept "*.exe" --content-disposition --trust-server-names http://download-hr.utorrent.com/track/stable/endpoint/utorrent/os/windows &> /dev/null
}

dli7z16x64 () {
    for dldebs in https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091326/+files/p7zip_16.02+dfsg-4_amd64.deb https://launchpad.net/ubuntu/+source/p7zip/16.02+dfsg-4/+build/13091326/+files/p7zip-full_16.02+dfsg-4_amd64.deb 
    do
    wget $dldebs &> /dev/null
    done

    for pkgdebins in p7zip_16.02+dfsg-4_amd64.deb p7zip-full_16.02+dfsg-4_amd64.deb
    do
    sudo apt install ./$pkgdebins -y &> /dev/null
    rm $pkgdebins
    done
}

mkut () {
    mkdir ./{wine-runtime,wine-platform,bin} && mkdir -p usr/share/{pixmaps,applications}
    7z x uTorrent.exe Carrier.exe -o"usr/share/utorrent"
    mv usr/share/utorrent/Carrier.exe usr/share/utorrent/utorrent.exe
    find "usr" -type d -execdir chmod 755 {} +
}

mkdsk () {
cat > utorrent.desktop <<'EOF1'
[Desktop Entry]
Name=µTorrent
GenericName=BitTorrent Client
Comment=The world's most popular BitTorrent client
Encoding=UTF-8
Version=3.5.5.45271
Type=Application
Terminal=false
Icon=${SNAP}/usr/share/pixmaps/utorrent.png
Exec=utorrent %U
StartupWMClass=utorrent.exe
Categories=Network;FileTransfer;P2P;
MimeType=application/x-bittorrent;x-scheme-handler/magnet;
EOF1
}

dlut
dli7z16x64
mkut
mkdsk
mv utorrent bin && mv utorrent.desktop usr/share/applications && mv utorrent.png usr/share/pixmaps && cp -R -p {bin,usr,wine-runtime,wine-platform} $SNAPCRAFT_PART_INSTALL