name: utorrent
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: utorrent is the no-1 BitTorrent download client on desktops worldwide.
description: |
 utorrent is a proprietary BitTorrent client owned and developed by BitTorrent, Inc. With over 100 million users it is the most widely used BitTorrent client. The program was designed to use minimal computer resources while offering functionality comparable to larger BitTorrent clients such as Vuze or BitComet.

confinement: devmode
grade: stable
architectures: [amd64, i386]

apps:
  utorrent:
    command: utorrent
    desktop: usr/share/applications/utorrent.desktop
    plugs: [ wayland, x11, opengl, home, desktop, desktop-legacy, network, network-observe, mount-observe, hardware-observe, process-control, cups-control, browser-support ]

parts:
  enable-i386:
    plugin: nil
    prepare: |
      dpkg --add-architecture i386
      apt update

  wine-3p1:
    after: [enable-i386]
    plugin: dump
    source: https://dl.winehq.org/wine-builds/ubuntu/pool/main/wine-stable-i386_3.0.0~xenial_i386.deb
    source-type: deb
    install: |
      spi=$SNAPCRAFT_PART_INSTALL
      lins=$spi/usr/share/lintian
      docs=$spi/usr/share/doc
      mans=$spi/usr/share/man
      ws=opt/wine-stable
      cp -r $ws/* $spi/ && cp -r $spi/share $spi/usr/ && rm -r $spi/opt $spi/share $mans $lins $docs
    stage-packages:
    - on i386:
      - libfreetype6
      - libpng12-0
      - libncurses5
      - libgnutls30
      - libxext6
      - libudev1
      - libc6
      - zlib1g
    - on amd64:
      - libfreetype6:i386
      - libpng12-0:i386
      - libncurses5:i386
      - libgnutls30:i386
      - libxext6:i386
      - libudev1:i386
      - libc6:i386
      - zlib1g:i386

  wine-3p2:
    plugin: dump
    source: https://dl.winehq.org/wine-builds/ubuntu/pool/main/wine-stable_3.0.0~xenial_i386.deb
    source-type: deb
    install: |
      spi=$SNAPCRAFT_PART_INSTALL
      docs=$spi/usr/share/doc
      mans=$spi/share/man
      ws="opt/wine-stable"
      cp -r $ws/* $spi/ && rm -r $spi/opt $docs $mans $spi/share/wine/fonts

  utorrent:
    install: |
      ver="$(wget http://www.utorrent.com/downloads/win -q -S -O - 2>&1 | grep Stable | awk '{print $2}' | sed 's|Stable(||')"
      bnum="$(wget http://www.utorrent.com/downloads/win -q -S -O - 2>&1 | grep Stable | awk '{print $4}' | sed 's|)||')"
      echo $ver.$bnum > $SNAPCRAFT_STAGE/version
    plugin: dump
    source: ./scripts
    prepare: ./dl_ut
    build-packages: [wget, icoutils, p7zip-full]
