name: utorrent
version: 3.5.5.44910
summary: utorrent is the no-1 BitTorrent download client on desktops worldwide.
description: |
 utorrent is a proprietary BitTorrent client owned and developed by BitTorrent, Inc. With over 100 million users it is the most widely used BitTorrent client. The program was designed to use minimal computer resources while offering functionality comparable to larger BitTorrent clients such as Vuze or BitComet.

confinement: strict
grade: stable
architectures:
  - build-on: amd64
    run-on: [amd64, i386]

plugs:
  wine-platform-plug:
    content: wine-base-stable
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform

apps:
  utorrent:
    command: utorrent
    desktop: usr/share/applications/utorrent.desktop
    plugs: [ wayland, x11, opengl, home, desktop, desktop-legacy, network, network-observe, mount-observe, hardware-observe, process-control, cups-control, browser-support, wine-platform-plug ]

parts:
  utorrent:
    plugin: nil
    source: ./scripts
    override-build: |
      snapcraftctl build
      set -ex
      ./dl_ut
    stage:
      - bin
      - usr
      - wine-platform
    build-packages: [wget, icoutils, p7zip-full]
